server:
  port: 6666
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.gaoh.modules.entity

#showSql
logging:
  level:
    com.gaoh: debug
    org.mybatis.spring: debug


stu:
  age: 24
  name: gaoh